#!/usr/bin/env python3
"""
PRODUCT MARKETER: SEO Content Generation Engine
Transforms researched product data into CMS-ready content packages.
"""

import json
import logging
import os
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import cloudinary
import cloudinary.uploader
from openai import OpenAI

logger = logging.getLogger(__name__)


@dataclass
class ContentPackage:
    """Content generated by GPT for a product."""
    seo_title: str
    meta_description: str
    narrative: str
    faqs: List[Dict[str, str]]
    seo_slug: str
    semantic_keywords: List[str] = field(default_factory=list)
    enhanced_product_description: str = ""


@dataclass
class MarketingResult:
    """Final marketing output for a product."""
    seo_slug: str
    cms_title: str
    cms_body_html: str
    meta_description: str
    faq_json_ld: Dict[str, Any]
    product_json_ld: Dict[str, Any]
    extracted_price: str
    images_renamed: int
    status: str
    notes: str = ""
    enhanced_product_description: str = ""


class ProductMarketer:
    """
    SEO Content Generation Engine.
    Generates CMS-ready content packages from researched product data.
    """

    # Price extraction patterns
    PRICE_PATTERNS = [
        r'工厂价\s*[:：]?\s*(\d+(?:\.\d{2})?)',        # 工厂价:330, 工厂价 310
        r'价格\s*[:：]?\s*(\d+(?:\.\d{2})?)',          # 价格:299, 价格：299
        r'售价\s*[:：]?\s*(\d+(?:\.\d{2})?)',          # 售价:299
        r'[¥￥]\s*(\d+(?:\.\d{2})?)',                  # ¥299, ￥ 299
        r'(\d+(?:\.\d{2})?)\s*[元块]',                 # 299元, 299块
        r'[rR][mM][bB]\s*[:：]?\s*(\d+(?:\.\d{2})?)',  # RMB: 299
        r'[pP]rice?\s*[:：]?\s*(\d+(?:\.\d{2})?)',     # price: 299, Price:299
        r'[\$]\s*(\d+(?:\.\d{2})?)',                   # $299
        r'(\d{2,4})\s*[yY]uan',                        # 299yuan, 299 Yuan
        r'💰\s*(\d+(?:\.\d{2})?)',                     # 💰299
        r'(\d+(?:\.\d{2})?)\s*💰',                     # 299💰
    ]

    def __init__(
        self,
        openai_api_key: str,
        cloudinary_cloud_name: str = '',
        cloudinary_api_key: str = '',
        cloudinary_api_secret: str = '',
    ):
        """
        Initialize ProductMarketer.

        Args:
            openai_api_key: OpenAI API key for GPT-4o
            cloudinary_cloud_name: Cloudinary cloud name
            cloudinary_api_key: Cloudinary API key
            cloudinary_api_secret: Cloudinary API secret
        """
        self.openai_client = OpenAI(api_key=openai_api_key)
        self.brand_name = os.getenv('CLIENT_BRAND_NAME', 'Luxearchive')

        if cloudinary_cloud_name:
            cloudinary.config(
                cloud_name=cloudinary_cloud_name,
                api_key=cloudinary_api_key,
                api_secret=cloudinary_api_secret,
            )

        # Run-level cost accumulators (reset per batch, reported to run_sessions)
        self._run_tokens: int = 0
        self._run_cost: float = 0.0

        logger.info("ProductMarketer initialized")

    def delete_main_image(self, product_id: str) -> bool:
        """
        Delete the research-only hero image (00_main) from Cloudinary.
        This image is used by Agent 2 for visual search and must be removed
        before Agent 4 processes the product to avoid confusion during publishing.

        Args:
            product_id: The product's unique ID

        Returns:
            True if deleted (or already gone), False on error
        """
        # Try both public_id forms: with and without the folder prefix.
        # Cloudinary may return either depending on account folder mode.
        candidates = [
            f"hollomen/{product_id}/00_main",
            f"hollomen/{product_id}/00_main.jpg",
        ]
        deleted = False
        for public_id in candidates:
            try:
                result = cloudinary.uploader.destroy(public_id, resource_type="image")
                if result.get('result') == 'ok':
                    logger.info(f"[IMAGES] Deleted research hero: {public_id}")
                    deleted = True
                    break
            except Exception as e:
                logger.warning(f"[IMAGES] Could not delete {public_id}: {e}")

        if not deleted:
            logger.info(f"[IMAGES] 00_main not found for {product_id} — Agent 4 will handle it")
        return True

    def extract_price(self, raw_text: str) -> str:
        """
        Extract price from Chinese supplier text.

        Args:
            raw_text: Raw Chinese text containing price information

        Returns:
            Extracted price as string (e.g., "299.00") or "0.00" if not found
        """
        if not raw_text:
            return "0.00"

        for pattern in self.PRICE_PATTERNS:
            match = re.search(pattern, raw_text)
            if match:
                price = match.group(1)
                # Ensure two decimal places
                if '.' not in price:
                    price = f"{price}.00"
                elif len(price.split('.')[1]) == 1:
                    price = f"{price}0"
                logger.info(f"[PRICE] Extracted: {price}")
                return price

        logger.info("[PRICE] No price found, using default 0.00")
        return "0.00"

    def generate_content(self, product_data: dict) -> ContentPackage:
        """
        Generate SEO content package using GPT-4o.

        Args:
            product_data: Dict with all available product fields from the sheet

        Returns:
            ContentPackage with all generated content
        """
        product_name = product_data.get('final_product_name', 'Unknown Product')
        designer_brand = product_data.get('designer_brand', self.brand_name)
        product_type = product_data.get('product_type', 'Footwear')
        material_info = product_data.get('material_info', 'Premium materials')
        product_description = product_data.get('product_description', '')
        english_translation = product_data.get('english_full_translation', '')
        raw_chinese = product_data.get('raw_chinese', '')
        research_sources = product_data.get('research_sources', '')
        research_source_links = product_data.get('research_source_links', '')
        existing_notes = product_data.get('notes', '')

        system_prompt = f"""You are an elite Luxury E-commerce SEO Copywriter for {self.brand_name}.
You write copy that RANKS and CONVERTS. Every sentence earns its place.

## Your Principles
1. **Keyword Integration:** Naturally weave target keywords into every piece of content. Never keyword-stuff, but ensure primary and secondary keywords appear in the narrative, meta description, and product description.
2. **Feature-Driven Selling:** Mine the manufacturer data for SPECIFIC features (materials, construction methods, aging processes, sole types) that differentiate the product. Generic copy kills conversions.
3. **Search Intent:** Match the buyer's mindset. Someone searching "Louis Vuitton Major Loafer" wants confirmation this is the real deal, material quality, and price signals. Someone searching "men's leather loafer" wants style versatility and comfort.
4. **CTA Always:** Every description and meta must end with a clear action trigger.

## Response Format (JSON only, no markdown)
{{
  "seo_title": "Under 60 chars. Brand + product type + key differentiator",
  "meta_description": "120-158 chars. Lead with keyword, mention 1-2 specific features, end with CTA. Example: 'Elevate your style with Men's Louis Vuitton Major Loafers. Leather aged for 3 months for richer texture. 100% cowhide leather. Check Price.'",
  "narrative": "150-180 words. CMS body text. Open with a hook, weave in keywords and specific product features from manufacturer data. Reference materials, construction, design details. End with soft CTA. NOT generic - this must read like it was written for THIS specific product.",
  "enhanced_product_description": "2-3 sentences. Upgrade the existing product description by incorporating target keywords and specific details. Keep it concise but SEO-rich.",
  "faqs": [
    {{"question": "Fit/sizing question specific to this product type", "answer": "Answer using manufacturer details"}},
    {{"question": "Material/care question referencing actual materials", "answer": "Answer with specific care instructions"}},
    {{"question": "Styling question for this product category", "answer": "Answer with outfit pairing suggestions"}}
  ],
  "seo_slug": "lowercase-hyphenated-max-60-chars",
  "semantic_keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5"]
}}"""

        # Build rich context from all available data
        context_parts = [f"- Product Name: {product_name}"]
        context_parts.append(f"- Brand: {designer_brand}")
        context_parts.append(f"- Product Type: {product_type}")
        context_parts.append(f"- Materials: {material_info}")

        if product_description:
            context_parts.append(f"- Current Product Description: {product_description}")
        if english_translation:
            context_parts.append(f"- Manufacturer Text (translated): {english_translation}")
        if raw_chinese:
            context_parts.append(f"- Original Chinese Text: {raw_chinese}")
        if research_sources:
            context_parts.append(f"- Verified Sources: {research_sources}")
        if existing_notes and 'Keywords:' in existing_notes:
            context_parts.append(f"- Existing Keywords: {existing_notes}")

        context_block = '\n'.join(context_parts)

        user_prompt = f"""Create a COMPLETE content package for this product. Use ALL the data below to write specific, feature-rich copy.

## Product Data
{context_block}

## Requirements

### SEO Title (max 60 chars)
Include brand name and product type. Add a differentiator if space allows.

### Meta Description (120-158 chars, max 920px)
- Lead with the primary keyword (brand + product type)
- Mention 1-2 SPECIFIC features from the manufacturer data (not generic "premium quality")
- End with a CTA ("Check Price", "Shop Now", "Explore the Collection")
- BAD: "Discover this amazing luxury shoe with premium materials. Shop now."
- GOOD: "Elevate your style with Men's Louis Vuitton Major Loafers. Leather aged for 3 months for richer texture. 100% cowhide leather. Check Price."

### Narrative (150-180 words)
- Open with a hook that names the product
- Mine the manufacturer text for UNIQUE selling points (construction method, leather type, sole material, design heritage)
- Weave in 3-5 semantic keywords naturally
- Reference the brand's design philosophy if from research sources
- End with a soft CTA
- DO NOT use filler words: very, amazing, stunning, exquisite, unparalleled, elevate
- Every sentence must contain product-specific information

### Enhanced Product Description (2-3 sentences)
Take the "Current Product Description" and rewrite it to include target keywords. Keep it concise, specific, and SEO-optimized.

### FAQs (3 Q&As)
Questions should be phrased as real customer search queries. Answers must reference actual product details, not generic advice.

### SEO Slug
Include brand, product type, and one differentiator. Max 60 chars.

### Semantic Keywords (5 keywords)
Primary + secondary keywords that should appear across the content.

Return ONLY valid JSON, no markdown formatting."""

        try:
            response = self.openai_client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.7,
                response_format={"type": "json_object"}
            )

            # Log token usage & estimated cost (GPT-4o: $2.50/1M input, $10.00/1M output)
            u = response.usage
            cost = (u.prompt_tokens / 1_000_000 * 2.50) + (u.completion_tokens / 1_000_000 * 10.00)
            self._run_tokens += u.total_tokens
            self._run_cost += cost
            logger.info(
                f"[COST][Agent3] prompt={u.prompt_tokens} completion={u.completion_tokens} "
                f"total={u.total_tokens} est_cost=${cost:.5f}"
            )

            content_json = json.loads(response.choices[0].message.content)

            return ContentPackage(
                seo_title=content_json.get('seo_title', product_name)[:60],
                meta_description=content_json.get('meta_description', '')[:160],
                narrative=content_json.get('narrative', ''),
                faqs=content_json.get('faqs', []),
                seo_slug=self._sanitize_slug(content_json.get('seo_slug', '')),
                semantic_keywords=content_json.get('semantic_keywords', []),
                enhanced_product_description=content_json.get('enhanced_product_description', '')
            )

        except json.JSONDecodeError as e:
            logger.error(f"[CONTENT] Invalid JSON response: {e}")
            raise
        except Exception as e:
            logger.error(f"[CONTENT] GPT generation failed: {e}")
            raise

    def _sanitize_slug(self, slug: str) -> str:
        """Ensure slug is valid URL format."""
        if not slug:
            return "product"

        # Lowercase, replace spaces with hyphens
        slug = slug.lower().strip()
        slug = re.sub(r'[^a-z0-9-]', '-', slug)
        slug = re.sub(r'-+', '-', slug)  # Multiple hyphens to single
        slug = slug.strip('-')  # Remove leading/trailing hyphens

        return slug[:60]  # Max 60 chars

    def build_html(self, content: ContentPackage) -> str:
        """
        Build CMS body HTML from content package.

        Args:
            content: ContentPackage with narrative and FAQs

        Returns:
            HTML string for CMS body
        """
        faq_html_parts = []
        for faq in content.faqs:
            faq_html_parts.append(f'''    <div class="faq-item">
      <h4>{faq.get('question', '')}</h4>
      <p>{faq.get('answer', '')}</p>
    </div>''')

        faq_html = '\n\n'.join(faq_html_parts)

        html = f'''<div class="product-description">
  <h2>{content.seo_title}</h2>
  <p class="narrative">{content.narrative}</p>

  <div class="product-faqs">
    <h3>Frequently Asked Questions</h3>

{faq_html}
  </div>
</div>'''

        return html

    def build_product_schema(
        self,
        product_name: str,
        brand: str,
        narrative: str,
        price: str,
        image_url: str = ""
    ) -> dict:
        """
        Build Product JSON-LD schema.

        Args:
            product_name: Full product name
            brand: Designer/brand name
            narrative: Product description
            price: Price as string
            image_url: URL to main product image

        Returns:
            Dict representing Product schema
        """
        # Extract first sentence for description
        first_sentence = narrative.split('.')[0] + '.' if narrative else product_name

        schema = {
            "@context": "https://schema.org",
            "@type": "Product",
            "name": product_name,
            "description": first_sentence,
            "brand": {
                "@type": "Brand",
                "name": brand
            },
            "offers": {
                "@type": "Offer",
                "price": price,
                "priceCurrency": "USD",
                "availability": "https://schema.org/InStock"
            }
        }

        if image_url:
            schema["image"] = image_url

        return schema

    def build_faq_schema(self, faqs: List[Dict[str, str]]) -> dict:
        """
        Build FAQPage JSON-LD schema.

        Args:
            faqs: List of {question, answer} dicts

        Returns:
            Dict representing FAQPage schema
        """
        main_entity = []
        for faq in faqs:
            main_entity.append({
                "@type": "Question",
                "name": faq.get('question', ''),
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": faq.get('answer', '')
                }
            })

        return {
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": main_entity
        }

    def process_product(self, row_data: dict) -> MarketingResult:
        """
        Process a single product through the full marketing pipeline.

        Args:
            row_data: Row data from Google Sheet

        Returns:
            MarketingResult with all generated content
        """
        product_id = row_data.get('product_id', 'UNKNOWN')
        logger.info(f"[PROCESS] Starting marketing for {product_id}")

        # Validate required fields
        required = ['final_product_name', 'designer_brand']
        missing = [f for f in required if not row_data.get(f)]
        if missing:
            return MarketingResult(
                seo_slug="",
                cms_title="",
                cms_body_html="",
                meta_description="",
                faq_json_ld={},
                product_json_ld={},
                extracted_price="0.00",
                images_renamed=0,
                status="SEO_FAILED",
                notes=f"Missing required fields: {', '.join(missing)}"
            )

        try:
            # Phase 1: Extract price
            raw_chinese = row_data.get('raw_chinese', '')
            price = self.extract_price(raw_chinese)

            # Phase 2: Generate content
            content = self.generate_content(row_data)

            # Phase 3: Build HTML
            cms_html = self.build_html(content)

            # Phase 4: Build schemas
            product_schema = self.build_product_schema(
                product_name=row_data.get('final_product_name'),
                brand=row_data.get('designer_brand'),
                narrative=content.narrative,
                price=price,
                image_url=""  # Could add main image URL here
            )

            faq_schema = self.build_faq_schema(content.faqs)

            # Phase 5: Delete research-only hero image from Cloudinary
            self.delete_main_image(product_id)

            # Build result
            return MarketingResult(
                seo_slug=content.seo_slug,
                cms_title=content.seo_title,
                cms_body_html=cms_html,
                meta_description=content.meta_description,
                faq_json_ld=faq_schema,
                product_json_ld=product_schema,
                extracted_price=price,
                images_renamed=0,
                status="COMPLETE",
                notes=f"Keywords: {', '.join(content.semantic_keywords)}",
                enhanced_product_description=content.enhanced_product_description
            )

        except Exception as e:
            logger.error(f"[PROCESS] Failed for {product_id}: {e}")
            # Re-raise so RetryableOperation can catch it, categorize it, and retry
            # transient errors (network timeouts, OpenAI rate limits, etc.).
            # Swallowing here would make every error look like a success=True/FAILED
            # result and bypass the retry machinery entirely.
            raise
